spring.application.name=SpringBootPracticeAll

spring.dataSource.url=  jdbc:mysql://localhost:3306/practiceAll
spring.dataSource.password=root
spring.dataSource.user=root


spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect