spring.application.name=SpringBootPracticeAll


spring.datasource.url = jdbc:mysql://localhost:3306/practiceAll
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jpa.properties.hibernate.format_sql=true;

 jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect